### ISSUE TITLE
Update version in setup.py

### ISSUE THREAD

**Issue by pallxk** [jml/tree-format#16]
I see that on [PyPI](https://pypi.org/project/tree-format/), this package is already at `0.1.2` on Nov 6, 2017, while version in this repo is still at `0.1.0`. Would you mind to update the version field in `setup.py` in this repo to be consistent with what's on PyPI and tag those published versions in git?

This matters for self packaging for users of Arch Linux using [AUR](https://aur.archlinux.org/packages/python-tree-format-git/).

Thanks

**Comment by jonathanj** [comment]
Closed by 922c9d3.
